import { Request, Response } from 'express';

const rootNode = {
  id: '0',
  title: '杭州市园文局 0',
  attributes: { mType: 'dept' },
  isDept: true,
  icon: null,
  children: [
    {
      id: '1-0',
      title: '局领导 1-0',
      isDept: true,
      attributes: { mType: 'dept' },
      hasChildren: true,
      hasParent: true,
      icon: null,
      parentId: '0',
      state: null,
      url: null,
      children: [
        {
          id: '1-0-0',
          title: '卡卡罗特 1-0-0',
          attributes: {
            mobile: '13906533982',
            userId: '1-0-0',
            mType: 'user',
          },
          checked: false,
          children: [],
          hasChildren: false,
          hasParent: true,
          icon: null,
          parentId: '1-0',
          state: null,
          url: null,
        },
        {
          id: '1-0-1',
          title: '他姓名 1-0-1',
          attributes: {
            mobile: '13906533982',
            userId: '1-0-1',
            mType: 'user',
          },
          checked: false,
          children: [],
          hasChildren: false,
          hasParent: true,
          icon: null,
          parentId: '1-0',
          state: null,
          url: null,
        },
        {
          id: '1-0-2',
          title: '他姓名 1-0-2',
          attributes: {
            mobile: '13906533982',
            userId: '1-0-2',
            mType: 'user',
          },
          checked: false,
          children: [],
          hasChildren: false,
          hasParent: true,
          icon: null,
          parentId: '1-0',
          state: null,
          url: null,
        },
      ],
    },
    {
      id: '1-1',
      title: '秘书处 1-1',
      isDept: true,
      attributes: { mType: 'dept' },
      hasChildren: true,
      hasParent: true,
      icon: null,
      parentId: '0',
      state: null,
      url: null,
      children: [
        {
          id: '1-1-0',
          title: '秘书处处长 1-1-0',
          isDept: true,
          attributes: { mType: 'dept' },
          hasChildren: true,
          hasParent: true,
          icon: null,
          parentId: '0',
          state: null,
          url: null,
          children: [
            {
              id: '1-1-0-0',
              title: '他姓名 1-1-0-0',
              attributes: {
                mobile: '13906533982',
                userId: '1-1-0-0',
                mType: 'user',
              },
              checked: false,
              children: [],
              hasChildren: false,
              hasParent: true,
              icon: null,
              parentId: '1-1-0',
              state: null,
              url: null,
            },
            {
              id: '1-1-1-1',
              title: '他姓名 1-1-1-1',
              attributes: {
                mobile: '13906533982',
                userId: '1-1-1-1',
                mType: 'user',
              },
              checked: false,
              children: [],
              hasChildren: false,
              hasParent: true,
              icon: null,
              parentId: '1-1-0',
              state: null,
              url: null,
            },
            {
              id: '1-1-2-2',
              title: '他姓名 1-1-2-2',
              attributes: {
                mobile: '13906533982',
                userId: '1-1-2-2',
                mType: 'user',
              },
              checked: false,
              children: [],
              hasChildren: false,
              hasParent: true,
              icon: null,
              parentId: '1-1-0',
              state: null,
              url: null,
            },
          ],
        },
        {
          id: '1-1-1',
          title: '他姓名1-1-1',
          isDept: true,
          attributes: { mType: 'dept' },
          hasChildren: true,
          hasParent: true,
          icon: null,
          parentId: '1-1',
          state: null,
          url: null,
        },
        {
          id: '1-1-2',
          title: '他姓名 1-1-2',
          isDept: true,
          attributes: { mType: 'dept' },
          hasChildren: true,
          hasParent: true,
          icon: null,
          parentId: '1-1',
          state: null,
          url: null,
        },
        {
          id: '1-1-3',
          title: '他姓名 1-1-3',
          isDept: true,
          attributes: { mType: 'dept' },
          hasChildren: true,
          hasParent: true,
          icon: null,
          parentId: '1-1',
          state: null,
          url: null,
        },
      ],
    },
  ],
};

function queryMemberListService(req: Request, res: Response, u: string) {
  const result = {
    code: '000000',
    data: rootNode,
  };

  return res.json(result);
}

export default {
  'POST /proxy/org/query/member': queryMemberListService,
};
